#!/usr/bin/env python3
"""Generate nmap_embedded_data.h from nmap's flat data files.

Each file is zlib-compressed (RFC1950, so the C side can use uncompress())
and emitted as a byte array plus a lookup-table entry. Run from the nmap
source directory; writes nmap_embedded_data.h next to it.
"""
import sys
import os
import zlib

# Flat data files nmap loads at runtime via nmap_fetchfile()+fopen().
# NSE (scripts/, nselib/, nse_main.lua) is intentionally excluded: it needs a
# real filesystem, which an in-memory fmemopen cannot provide.
DATA_FILES = [
    "nmap-services",
    "nmap-service-probes",
    "nmap-os-db",
    "nmap-protocols",
    "nmap-rpc",
    "nmap-mac-prefixes",
]


def emit_array(out, symbol, blob):
    out.write("static const unsigned char %s[] = {\n" % symbol)
    for i in range(0, len(blob), 20):
        chunk = blob[i:i + 20]
        out.write("  " + ",".join("%d" % b for b in chunk) + ",\n")
    out.write("};\n")


def main():
    srcdir = sys.argv[1] if len(sys.argv) > 1 else "."
    outpath = sys.argv[2] if len(sys.argv) > 2 else "nmap_embedded_data.h"

    entries = []
    with open(outpath, "w") as out:
        out.write("/* Auto-generated by gen_embedded_data.py. Do not edit. */\n")
        out.write("#ifndef NMAP_EMBEDDED_DATA_H\n#define NMAP_EMBEDDED_DATA_H\n\n")
        out.write("struct NmapEmbeddedFile {\n")
        out.write("  const char *name;\n")
        out.write("  const unsigned char *data;\n")
        out.write("  unsigned int gzlen;\n")
        out.write("  unsigned int rawlen;\n};\n\n")

        for idx, name in enumerate(DATA_FILES):
            path = os.path.join(srcdir, name)
            if not os.path.isfile(path):
                sys.stderr.write("gen_embedded_data: missing %s\n" % path)
                return 1
            with open(path, "rb") as f:
                raw = f.read()
            comp = zlib.compress(raw, 9)
            sym = "nmap_emb_%d" % idx
            emit_array(out, sym, comp)
            out.write("\n")
            entries.append((name, sym, len(comp), len(raw)))

        out.write("static const struct NmapEmbeddedFile g_nmap_embedded[] = {\n")
        for name, sym, gzlen, rawlen in entries:
            out.write('  { "%s", %s, %du, %du },\n' % (name, sym, gzlen, rawlen))
        out.write("};\n")
        out.write("static const int g_nmap_embedded_count = %d;\n\n" % len(entries))
        out.write("#endif\n")

    total_gz = sum(e[2] for e in entries)
    total_raw = sum(e[3] for e in entries)
    sys.stderr.write("gen_embedded_data: %d files, %d -> %d bytes (%.1f%%)\n"
                     % (len(entries), total_raw, total_gz,
                        100.0 * total_gz / total_raw if total_raw else 0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
