#!/usr/bin/env python3
# Compress a WAD with raw DEFLATE and emit a C header holding the compressed
# bytes plus the original length, for the puff-based embedded loader.
# Usage: gen_wad_header.py <input.wad> <output_header.h>
import sys, zlib

if len(sys.argv) != 3:
    sys.stderr.write("usage: gen_wad_header.py <input.wad> <output.h>\n")
    sys.exit(1)

raw = open(sys.argv[1], "rb").read()
co = zlib.compressobj(9, zlib.DEFLATED, -15)   # raw deflate (no zlib header/trailer) — puff expects this
comp = co.compress(raw) + co.flush()

with open(sys.argv[2], "w") as f:
    f.write("/* Auto-generated by gen_wad_header.py -- do not edit. */\n")
    f.write("static const unsigned long doom_wad_orig_len = %dUL;\n" % len(raw))
    f.write("static const unsigned long doom_wad_deflated_len = %dUL;\n" % len(comp))
    f.write("static const unsigned char doom_wad_deflated[] = {\n")
    for i in range(0, len(comp), 20):
        f.write("  " + ",".join("0x%02x" % b for b in comp[i:i+20]) + ",\n")
    f.write("};\n")

sys.stderr.write("embedded WAD: %d -> %d bytes (%.1f%%)\n"
                 % (len(raw), len(comp), 100.0 * len(comp) / len(raw)))
